name: Continuous Integration (macOS)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: ci
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install LF toolchain
        uses: lf-lang/action-setup-lf@v0.1
        with:
          lfc-version: stable
          lingo-version: stable
        
      - name: Install deps
        run: |
          brew tap osrf/simulation
          brew install gz-harmonic
          breq install eigen
      - name: Build examples
        run: |
          lfc src/*.lf